cubitt-postgresql:
  image: postgres:latest
  environment:
    POSTGRES_PASSWORD: cubitt
    POSTGRES_USER: cubitt
    POSTGRES_DB: cubitt
  expose:
    - "5432"
cubitt-platform:
  build: https://github.com/uu-cubitt/platform.git
  environment:
      POSTGRES_PASSWORD: cubitt
      POSTGRES_USER: cubitt
      POSTGRES_DB: cubitt
      POSTGRES_HOST: cubitt-postgresql
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://cubitt:cubitt@cubitt-postgresql/cubitt
  links:
    - cubitt-postgresql
  ports:
    - "8080:8080"
